posts = [
  {
    title: "Cat Attack",
    author: "Steve",
    url: "http://img07.deviantart.net/43cc/i/2002/34/1/d/clumsy_cat.jpg",
    description: "Vicious cat attack on innocent sleeping dog",
    date: Date.now()-500000000,
    votes: 5,
    comments: [{name: "Steve", content: "This is a comment"}, {name: "Guy", content: "What are you talking about!"}],
  },
  {
    title: "Dino-Myte",
    author: "Guy",
    url: "http://www.margothovley.com/wp-content/uploads/2012/03/homework-class-test-school-of-fail-the-thesaurus-was-the-mightiest-beast-of-the-dinosaur-kingdom.jpg",
    description: "Breaking news!  It's a new dinosaur!",
    date: Date.now(),
    votes: 1,
    comments: [{name: "Steve", content: "Angular Rocks"}, {name: "Dinoman", content: "Hah, that's hilarious"}],
  },
  {
    title: "Silicon Valley",
    author: "Pied Piper",
    url: "https://media2.giphy.com/media/dbHS31nm21uAU/200.gif",
    description: "Welcome and hey",
    date: Date.now()-300000000,
    votes: -4,
    comments: [{name: "Steve", content: "Angular Rocks"}],
  },
  {
    title: "New Dino",
    author: "Guy",
    url: "http://www.margothovley.com/wp-content/uploads/2012/03/homework-class-test-school-of-fail-the-thesaurus-was-the-mightiest-beast-of-the-dinosaur-kingdom.jpg",
    description: "Breaking news!  It's a new dinosaur!",
    date: Date.now()-509900000,
    votes: 0,
    comments: [],
  },
  {
    title: "New Dinosaur Discovered",
    author: "Guy",
    url: "http://www.margothovley.com/wp-content/uploads/2012/03/homework-class-test-school-of-fail-the-thesaurus-was-the-mightiest-beast-of-the-dinosaur-kingdom.jpg",
    description: "Breaking news!  It's a new dinosaur!",
    date: Date.now()-100000000,
    votes: 4,
    comments: [{name: "Steve", content: "Angular Rocks"}, {name: "Dinoman", content: "Hah, that's hilarious"}, {name: "Dinoman", content: "But really, it's great"}],
  },
];
